id: P003130
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG3973
  title: འཇའ་ཚོན་པོད་དྲུག་གི་དབང་དཔེ།
  author: ''
  volumes:
    124f2466ef17497db24a77589ac6d055:
      image_group_id: I1KG4040
      title: ''
      volume_number: 1
      total_pages: 698
      base_file: v001.txt
